version: '3.8'
services:
  app:
    build: .
    working_dir: /app
    volumes:
      - ./:/app
    command: >
      uvicorn routers.register:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5s
      timeout: 2s
      retries: 10
  test:
    image: python:3.8-slim
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - BASE_URL=http://app:8000
    command: >
      sh -c "pip install -r requirements.txt && sleep 10 && pytest --junitxml=tests/report.xml tests/basic_requests_test.py && cp tests/report.xml /app/tests/docker_report.xml"


