name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest requests httpx
    - name: Run application
      run: |
        uvicorn routers.register:app --host 0.0.0.0 --port 8000 &
        sleep 5
        for i in {1..30}; do
          if curl -s http://0.0.0.0:8000/health > /dev/null; then
            echo "Server is up!"
            break
          fi
          echo "Waiting for server ($i)..."
          sleep 1
        done
        if ! curl -s http://0.0.0.0:8000/health > /dev/null; then
          echo "Server did not start in time." && exit 1
        fi
    - name: Run requests-based tests
      run: |
        pytest tests/basic_requests_test.py --junitxml=tests/report.xml
    - name: Upload test report
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: tests/report.xml
    - name: Update test file for Docker
      run: |
        sed -i 's|http://host.docker.internal:8000/register|http://localhost:8000/register|g' tests/basic_requests_test.py
    - name: Run tests against Dockerized app
      run: |
        pytest tests/basic_requests_test.py --junitxml=tests/report.xml
    - name: Upload Docker test report
      uses: actions/upload-artifact@v4
      with:
        name: docker-test-report
        path: tests/report.xml
