name: Python application

on:
  push:
    branches: [ main, simple_user_registration ]
  pull_request:
    branches: [ main, simple_user_registration ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ./espresso_engine 
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    - name: Create .env file from GitHub Secrets
      run: |
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> espresso_engine/.env
    - name: Install backend dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r espresso_engine/requirements.txt

    - name: Build frontend
      run: |
        cd café-ui/first-sip-station
        npm install
        npm run build
        cd ../../..

    - name: Copy frontend build to backend static folder
      run: |
        mkdir -p espresso_engine/static
        cp -r café-ui/first-sip-station/dist/* espresso_engine/static/

    - name: Create release artifact
      run: |
        mkdir -p release-artifact
        cp -r espresso_engine release-artifact/
        cp requirements.txt release-artifact/
        cp web.config release-artifact/ || true

    - name: Publish release artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-artifact
        path: release-artifact
