name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest requests httpx
    - name: Run application
      run: |
        uvicorn routers.register:app --host 0.0.0.0 --port 8000 &
        sleep 10
    - name: Run requests-based tests
      run: |
        pytest tests/basic_requests_test.py --junitxml=tests/report.xml
    - name: Upload test report
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: tests/report.xml
